info:
  contact: {}
paths:
  /create:
    post:
      consumes:
      - application/json
      description: It will create a product from provided information
      operationId: create-product
      parameters:
      - description: DisplayId of a product
        in: body
        name: displayId
        required: true
        schema:
          type: string
      - description: Name of a product
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: Description of a product
        in: body
        name: description
        required: true
        schema:
          type: string
      responses:
        "250":
          description: A product is created. ErrorTypes array will be empty.
          schema:
            allOf:
            - type: object
            - properties:
                errorTypes:
                  items:
                    type: integer
                  type: array
              type: object
        "251":
          description: All ready a product with displayId or name. ErrorType{1 =>
            displayId, 2 => name}
          schema:
            allOf:
            - type: object
            - properties:
                errorTypes:
                  items:
                    type: integer
                  type: array
              type: object
      summary: Create a product
  /readbulk:
    get:
      consumes:
      - application/json
      description: It will collect primary data for products
      operationId: read-bulk
      parameters:
      - description: pageNumber of products bulk data
        in: body
        name: pagenumber
        required: true
        schema:
          type: integer
      - description: pageSize of products bulk data
        in: body
        name: pagesize
        required: true
        schema:
          type: integer
      - description: orderBy of products bulk data
        in: body
        name: orderby
        required: true
        schema:
          type: string
      - description: isOrderbyIncreasing of products bulk data
        in: body
        name: isorderbyincreasing
        required: true
        schema:
          type: boolean
      responses:
        "250":
          description: Products bulk data
          schema:
            allOf:
            - type: object
            - properties:
                products:
                  items:
                    type: object
                  type: array
              type: object
      summary: Read bulk data for products
  /readdisplaycard:
    get:
      consumes:
      - application/json
      description: It will collect primary data for display card for a product
      operationId: read-display-card-product
      parameters:
      - description: Id of a product
        in: body
        name: Id
        required: true
        schema:
          type: integer
      responses:
        "250":
          description: Display card data of a product
          schema:
            allOf:
            - type: object
            - properties:
                product:
                  type: object
              type: object
        "251":
          description: No product found with this id
          schema:
            allOf:
            - type: object
            - properties:
                errorTypes:
                  items:
                    type: integer
                  type: array
              type: object
      summary: Read data for display card for a product
swagger: "2.0"
